logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    com.nimbusds: DEBUG
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: springboot
spring:
  redis:
    host: localhost
    port: 6379
    # password: your_redis_password   # Uncomment and set if needed
mid:
  client:
    host-url: "https://tsp.demo.sk.ee/mid-api"
    relying-party-uuid: "00000000-0000-0000-0000-000000000000"
    relying-party-name: "DEMO"
    trust-store: /repo/vscode/backend/config/keystore.p12
    trust-store-password: "changeit"
    trust-store-type: "PKCS12"
