logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    com.nimbusds: DEBUG
    ee.sk.smartid.rest.LoggingFilter: debug
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: springboot
spring:
  redis:
    host: localhost
    port: 6379
    # password: your_redis_password   # Uncomment and set if needed
mid:
  client:
    host-url: "https://tsp.demo.sk.ee/mid-api"
    relying-party-uuid: "00000000-0000-0000-0000-000000000000"
    relying-party-name: "DEMO"
    trust-store: /repo/vscode/backend/config/mobileId.p12
    trust-store-password: "changeit"
    trust-store-type: "PKCS12"
smartid:
  client:
    host-url: "https://sid.demo.sk.ee/smart-id-rp/v2/"
    relying-party-uuid: "00000000-0000-0000-0000-000000000000"
    relying-party-name: "DEMO"
    trust-store: /repo/vscode/backend/config/smartId.p12
    trust-store-password: "changeit"
    trust-store-type: "PKCS12"
    ca-certs:
      - /repo/vscode/backend/config/sid_demo_sk_ee.crt
      - /repo/vscode/backend/config/sid_demo_sk_ee2.crt
webeid:
  ca-certs:
    - /repo/vscode/backend/config/EE_Certification_Center_Root_CA.pem
    - /repo/vscode/backend/config/ESTEID-SK_2015.pem
    - /repo/vscode/backend/config/esteid2018.pem
  allowed-origin: "https://localhost:3000"
oidc:
  issuer: "https://localhost:8443"
