logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    com.nimbusds: DEBUG
    ee.sk.smartid.rest.LoggingFilter: debug
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: springboot
spring:
  redis:
    host: localhost
    port: 6379
    # password: your_redis_password   # Uncomment and set if needed
mid:
  client:
    host-url: "https://tsp.demo.sk.ee/mid-api"
    relying-party-uuid: "00000000-0000-0000-0000-000000000000"
    relying-party-name: "DEMO"
    trust-store: /repo/vscode/backend/config/idcard.p12
    trust-store-password: ""
    api-trust-store: /repo/vscode/backend/config/smartId_api.p12
    api-trust-store-password: ""
smartid:
  client:
    host-url: "https://sid.demo.sk.ee/smart-id-rp/v2/"
    relying-party-uuid: "00000000-0000-0000-0000-000000000000"
    relying-party-name: "DEMO"
    trust-store: /repo/vscode/backend/config/idcard.p12    
    trust-store-password: ""
    api-trust-store: /repo/vscode/backend/config/smartId_api.p12
    api-trust-store-password: ""
    allowed-interaction-text: "Log in to self-service?"
    certificate-level: "QUALIFIED"
webeid:
  ca-keystore: /repo/vscode/backend/config/idcard.p12
  ca-keystore-password: ""
oidc:
  issuer: "https://localhost:8443"
